In [1]:
import numpy as np
np.__version__

'2.2.6'

In [2]:
# Conver list intop array because array is fast compared to list
ls=[1,2,3]
np.array(ls)

array([1, 2, 3])

In [3]:
ls=[1,2,3]
arr=np.array(ls)
type(arr)

numpy.ndarray

In [4]:
arr.ndim

1

In [5]:
arr.size

3

In [6]:
arr.shape

(3,)

In [7]:
ls1=[1,2.5,6.0]
np.array(ls1)  # Converts all integers to floating



array([1. , 2.5, 6. ])

In [8]:
np.array([2,4,6,2.5, 2+5j]) # All values is converted to complex number

array([2. +0.j, 4. +0.j, 6. +0.j, 2.5+0.j, 2. +5.j])

In [9]:
np.array([2,4,6,2.5], dtype='int') # Converts all to integer

array([2, 4, 6, 2])

In [10]:
np.array([2,4,6,2.5], dtype='str') # Converts all to string but for complex we cannot convert complex to float or integer

array(['2', '4', '6', '2.5'], dtype='<U3')

In [11]:
# 3d Array
arr2=np.array([[12,43,23],
         [2,43,23],
         [120,43,23]])
arr2

array([[ 12,  43,  23],
       [  2,  43,  23],
       [120,  43,  23]])

In [12]:
arr2.ndim

2

In [13]:
np.array([[12,43,23],
         [2,43,23],
         [120,43,np.nan]])  # Used to denote missing values (np.nan)

array([[ 12.,  43.,  23.],
       [  2.,  43.,  23.],
       [120.,  43.,  nan]])

In [14]:
np.array([[12,43,23],
         [2,43,23],
         [120,43,None]])  # Used to denote missing values as object (None)

array([[12, 43, 23],
       [2, 43, 23],
       [120, 43, None]], dtype=object)

In [15]:
# list(range(1.5,11.5)) # Range fn only works with integer values not floating so we use (arange) for this
# Gives error

In [16]:
np.arange(1.5,11.5)

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [17]:
np.arange(1.5,11.5,2)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [18]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# COnverting to 3*2
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
arr.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [21]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# COnvert n dimensional array in one dimensional
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones([2,3], dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
np.zeros([2,3,4])


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [27]:
np.full(10,7) #generate 10 elements with 7 nmumber


array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [28]:
np.full([2,3],5)


array([[5, 5, 5],
       [5, 5, 5]])

In [29]:
np.full([2,3],[7,8,9])

array([[7, 8, 9],
       [7, 8, 9]])

In [30]:
# Create Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(3)  #eve or identity method to generate identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.random.randint(1,10,5) # Generates random 5 numbers between given range i.e., 1 to 10 

array([6, 9, 8, 8, 4], dtype=int32)

In [33]:
np.random.randint(100,200,[3,4])

array([[142, 148, 119, 115],
       [101, 172, 159, 119],
       [130, 199, 160, 152]], dtype=int32)

In [34]:
np.random.rand(5)

array([0.83071771, 0.04517995, 0.37506396, 0.88061245, 0.67339029])

In [35]:
np.random.rand(1,10,5) #  For Unifrom distribution we use rand


array([[[0.23067834, 0.09856324, 0.84440912, 0.57708117, 0.1277098 ],
        [0.01697775, 0.2669586 , 0.37320132, 0.66686453, 0.52684403],
        [0.72900206, 0.44476818, 0.17738352, 0.74515043, 0.37221674],
        [0.35110864, 0.29807836, 0.76005358, 0.28546412, 0.4932649 ],
        [0.77134974, 0.39838489, 0.63764843, 0.99413388, 0.45176646],
        [0.18955363, 0.7186345 , 0.12936303, 0.0966321 , 0.74995111],
        [0.09757031, 0.29917296, 0.95833352, 0.3233861 , 0.76988139],
        [0.64110437, 0.67789209, 0.19848821, 0.09078306, 0.88739233],
        [0.80562109, 0.63184908, 0.80389015, 0.26443676, 0.43621112],
        [0.10806179, 0.49499658, 0.35986168, 0.06086681, 0.84683979]]])

In [36]:
np.random.rand(5)  #All values from output follows normal distribution

array([0.24771041, 0.54262501, 0.11335535, 0.17263971, 0.30453855])

In [37]:
np.linspace(1,10,5) 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [38]:
np.linspace(2,5, retstep=True) # Gives same difference

(array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
        2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
        2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
        2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
        3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
        3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
        3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
        4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
        4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
        4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ]),
 np.float64(0.061224489795918366))

In [39]:
arr = np.arange(1, 11).reshape(2, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
new_arr=arr.view()
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
arr[0][0]=100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [42]:
new_arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [43]:
new_arr_copy=arr.copy()
new_arr_copy

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [44]:
arr[0][0]=1000
arr

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])

In [45]:
new_arr_copy

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])